FROM ubuntu:bionic
LABEL maintainer="Gorav Bhootra <email@gorav.in>"

# https://github.com/docker-library/buildpack-deps/blob/master/bionic/curl/Dockerfile
#


RUN apt-get update && apt-get install -y --no-install-recommends \
		ca-certificates \
		curl \
		netbase \
		wget \
	&& rm -rf /var/lib/apt/lists/*

RUN set -ex; \
	if ! command -v gpg > /dev/null; then \
		apt-get update; \
		apt-get install -y --no-install-recommends \
			gnupg \
			dirmngr \
		; \
		rm -rf /var/lib/apt/lists/*; \
fi
